#!/bin/bash
# Shared logging helpers.

DOTFILES_COLOR_GREEN="${DOTFILES_COLOR_GREEN:-\033[0;32m}"
DOTFILES_COLOR_BLUE="${DOTFILES_COLOR_BLUE:-\033[0;34m}"
DOTFILES_COLOR_YELLOW="${DOTFILES_COLOR_YELLOW:-\033[1;33m}"
DOTFILES_COLOR_RED="${DOTFILES_COLOR_RED:-\033[0;31m}"
DOTFILES_COLOR_RESET="${DOTFILES_COLOR_RESET:-\033[0m}"

log_info() {
    echo -e "${DOTFILES_COLOR_BLUE}==>${DOTFILES_COLOR_RESET} $1"
}

log_success() {
    echo -e "${DOTFILES_COLOR_GREEN}OK${DOTFILES_COLOR_RESET} $1"
}

log_warning() {
    echo -e "${DOTFILES_COLOR_YELLOW}WARN${DOTFILES_COLOR_RESET} $1"
}

log_error() {
    echo -e "${DOTFILES_COLOR_RED}ERR${DOTFILES_COLOR_RESET} $1"
}
