#!/bin/bash
# Configure package-manager mirrors only when no domestic mirror is detected.

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
export DOTFILES_DIR

# shellcheck disable=SC1091
source "$DOTFILES_DIR/scripts/lib/common.sh"
# shellcheck disable=SC1091
source "$DOTFILES_DIR/scripts/detect_os.sh"

FORCE_MIRRORS=false
YES=false
DRY_RUN=false

usage() {
    cat <<'EOF'
Usage: setup_mirrors.sh [--force] [--yes] [--dry-run]

Options:
  --force    Rewrite mirror config even when domestic mirrors are detected.
  --yes      Do not prompt before writing mirror config.
  --dry-run  Print actions without writing files.
EOF
}

parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --force)
                FORCE_MIRRORS=true
                ;;
            --yes|-y)
                YES=true
                ;;
            --dry-run)
                DRY_RUN=true
                ;;
            --help|-h)
                usage
                exit 0
                ;;
            *)
                log_error "未知参数: $1"
                usage
                exit 1
                ;;
        esac
        shift
    done
}

confirm_write() {
    local message="$1"

    if [ "$YES" = true ] || [ "$DRY_RUN" = true ]; then
        return 0
    fi

    read -r -p "$message (y/N) " reply
    [[ "$reply" =~ ^[Yy]$ ]]
}

is_domestic_mirror_file() {
    local file="$1"

    [ -f "$file" ] || return 1
    grep -Eiq 'mirrors\.aliyun\.com|mirrors\.tuna\.tsinghua\.edu\.cn|mirrors\.ustc\.edu\.cn|mirrors\.nju\.edu\.cn|mirrors\.163\.com|repo\.huaweicloud\.com|mirrors\.cloud\.tencent\.com' "$file"
}

backup_file() {
    local file="$1"

    [ -f "$file" ] || return 0
    if [ "$DRY_RUN" = true ]; then
        log_info "DRY-RUN: backup $file -> ${file}.backup.<timestamp>"
        return 0
    fi

    sudo cp "$file" "${file}.backup.$(date +%Y%m%d_%H%M%S)"
    log_success "已备份: $file"
}

apt_has_domestic_mirror() {
    local file

    for file in /etc/apt/sources.list /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
        [ -f "$file" ] || continue
        if is_domestic_mirror_file "$file"; then
            return 0
        fi
    done

    return 1
}

apt_codename() {
    local codename=""

    if command_exists lsb_release; then
        codename="$(lsb_release -cs 2>/dev/null || true)"
    fi

    if [ -z "$codename" ] && [ -f /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
        codename="${VERSION_CODENAME:-}"
    fi

    echo "$codename"
}

setup_apt_mirror() {
    local os="$1"
    local codename

    if [ "$FORCE_MIRRORS" != true ] && apt_has_domestic_mirror; then
        log_success "已检测到 apt 国内镜像源，跳过"
        return 0
    fi

    codename="$(apt_codename)"
    if [ -z "$codename" ]; then
        log_warning "无法识别系统版本代号，跳过 apt 镜像源配置"
        return 0
    fi

    if ! confirm_write "将写入阿里云 apt 镜像源到 /etc/apt/sources.list"; then
        log_warning "跳过 apt 镜像源配置"
        return 0
    fi

    backup_file /etc/apt/sources.list

    if [ "$DRY_RUN" = true ]; then
        log_info "DRY-RUN: write /etc/apt/sources.list for $os $codename"
        return 0
    fi

    if [ "$os" = "ubuntu" ]; then
        cat <<EOF | sudo tee /etc/apt/sources.list >/dev/null
# 阿里云 Ubuntu 镜像源
deb https://mirrors.aliyun.com/ubuntu/ ${codename} main restricted universe multiverse
deb https://mirrors.aliyun.com/ubuntu/ ${codename}-updates main restricted universe multiverse
deb https://mirrors.aliyun.com/ubuntu/ ${codename}-backports main restricted universe multiverse
deb https://mirrors.aliyun.com/ubuntu/ ${codename}-security main restricted universe multiverse
EOF
    else
        cat <<EOF | sudo tee /etc/apt/sources.list >/dev/null
# 阿里云 Debian 镜像源
deb https://mirrors.aliyun.com/debian/ ${codename} main contrib non-free non-free-firmware
deb https://mirrors.aliyun.com/debian/ ${codename}-updates main contrib non-free non-free-firmware
deb https://mirrors.aliyun.com/debian/ ${codename}-backports main contrib non-free non-free-firmware
deb https://mirrors.aliyun.com/debian-security/ ${codename}-security main contrib non-free non-free-firmware
EOF
    fi

    log_success "apt 镜像源配置完成"
}

pacman_has_domestic_mirror() {
    is_domestic_mirror_file /etc/pacman.d/mirrorlist
}

setup_pacman_mirror() {
    if [ "$FORCE_MIRRORS" != true ] && pacman_has_domestic_mirror; then
        log_success "已检测到 pacman 国内镜像源，跳过"
        return 0
    fi

    if ! confirm_write "将写入 pacman 国内镜像源到 /etc/pacman.d/mirrorlist"; then
        log_warning "跳过 pacman 镜像源配置"
        return 0
    fi

    backup_file /etc/pacman.d/mirrorlist

    if [ "$DRY_RUN" = true ]; then
        log_info "DRY-RUN: write /etc/pacman.d/mirrorlist"
        return 0
    fi

    cat <<'EOF' | sudo tee /etc/pacman.d/mirrorlist >/dev/null
## China mirrors generated by dotfiles
Server = https://mirrors.aliyun.com/archlinux/$repo/os/$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.163.com/archlinux/$repo/os/$arch
EOF

    log_success "pacman 镜像源配置完成"
}

setup_fedora_mirror() {
    log_warning "Fedora repo 自动改写暂未启用，避免误改 /etc/yum.repos.d"
    log_info "如需配置镜像源，请参考 docs/install/README.md"
}

main() {
    parse_args "$@"

    local os
    os="$(detect_os)"
    log_info "检测到系统: $os"

    case "$os" in
        ubuntu|debian)
            setup_apt_mirror "$os"
            ;;
        arch|manjaro)
            setup_pacman_mirror
            ;;
        fedora)
            setup_fedora_mirror
            ;;
        macos)
            log_warning "macOS 镜像源由 Homebrew 管理，本脚本不处理"
            ;;
        *)
            log_warning "暂不支持该系统的镜像源自动配置: $os"
            ;;
    esac
}

if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then
    main "$@"
fi
