#!/bin/bash
# 镜像源配置脚本 - 针对中国大陆环境优化

set -e

# 颜色输出
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}==>${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# 备份原有镜像源配置
backup_sources() {
    local file="$1"
    if [ -f "$file" ]; then
        sudo cp "$file" "${file}.backup.$(date +%Y%m%d_%H%M%S)"
        log_success "已备份原有配置: $file"
    fi
}

# 配置 Arch Linux 镜像源
setup_arch_mirrors() {
    log_info "配置 Arch Linux 镜像源..."

    backup_sources "/etc/pacman.d/mirrorlist"

    # 使用阿里云、清华、中科大镜像
    cat <<'EOF' | sudo tee /etc/pacman.d/mirrorlist > /dev/null
##
## Arch Linux repository mirrorlist
## Generated by dotfiles setup script
##

## China - Aliyun
Server = https://mirrors.aliyun.com/archlinux/$repo/os/$arch

## China - Tsinghua
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch

## China - USTC
Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch

## China - 163
Server = https://mirrors.163.com/archlinux/$repo/os/$arch

## China - Huawei
Server = https://repo.huaweicloud.com/archlinux/$repo/os/$arch
EOF

    # 配置 archlinuxcn 源
    if ! grep -q "\[archlinuxcn\]" /etc/pacman.conf; then
        log_info "添加 archlinuxcn 源..."
        cat <<'EOF' | sudo tee -a /etc/pacman.conf > /dev/null

[archlinuxcn]
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
EOF
    fi

    log_success "Arch Linux 镜像源配置完成"
}

# 配置 Ubuntu/Debian 镜像源
setup_ubuntu_mirrors() {
    log_info "配置 Ubuntu 镜像源..."

    backup_sources "/etc/apt/sources.list"

    # 获取 Ubuntu 版本代号
    local codename=$(lsb_release -cs)

    # 使用阿里云镜像
    cat <<EOF | sudo tee /etc/apt/sources.list > /dev/null
# 阿里云镜像源
deb https://mirrors.aliyun.com/ubuntu/ ${codename} main restricted universe multiverse
deb https://mirrors.aliyun.com/ubuntu/ ${codename}-updates main restricted universe multiverse
deb https://mirrors.aliyun.com/ubuntu/ ${codename}-backports main restricted universe multiverse
deb https://mirrors.aliyun.com/ubuntu/ ${codename}-security main restricted universe multiverse

# 清华镜像源（备用）
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename} main restricted universe multiverse
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-updates main restricted universe multiverse
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-backports main restricted universe multiverse
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ ${codename}-security main restricted universe multiverse
EOF

    log_success "Ubuntu 镜像源配置完成"
}

# 配置 Debian 镜像源
setup_debian_mirrors() {
    log_info "配置 Debian 镜像源..."

    backup_sources "/etc/apt/sources.list"

    # 获取 Debian 版本代号
    local codename=$(lsb_release -cs)

    # 使用阿里云镜像
    cat <<EOF | sudo tee /etc/apt/sources.list > /dev/null
# 阿里云镜像源
deb https://mirrors.aliyun.com/debian/ ${codename} main contrib non-free non-free-firmware
deb https://mirrors.aliyun.com/debian/ ${codename}-updates main contrib non-free non-free-firmware
deb https://mirrors.aliyun.com/debian/ ${codename}-backports main contrib non-free non-free-firmware
deb https://mirrors.aliyun.com/debian-security/ ${codename}-security main contrib non-free non-free-firmware

# 清华镜像源（备用）
# deb https://mirrors.tuna.tsinghua.edu.cn/debian/ ${codename} main contrib non-free non-free-firmware
# deb https://mirrors.tuna.tsinghua.edu.cn/debian/ ${codename}-updates main contrib non-free non-free-firmware
# deb https://mirrors.tuna.tsinghua.edu.cn/debian/ ${codename}-backports main contrib non-free non-free-firmware
# deb https://mirrors.tuna.tsinghua.edu.cn/debian-security/ ${codename}-security main contrib non-free non-free-firmware
EOF

    log_success "Debian 镜像源配置完成"
}

# 配置 Fedora 镜像源
setup_fedora_mirrors() {
    log_info "配置 Fedora 镜像源..."

    # Fedora 使用 metalink，需要修改 repo 文件
    local repo_dir="/etc/yum.repos.d"

    # 备份原有配置
    if [ -d "$repo_dir" ]; then
        sudo cp -r "$repo_dir" "${repo_dir}.backup.$(date +%Y%m%d_%H%M%S)"
    fi

    # 禁用 metalink，启用 baseurl
    for repo_file in "$repo_dir"/fedora*.repo; do
        if [ -f "$repo_file" ]; then
            sudo sed -i 's/^metalink=/#metalink=/g' "$repo_file"
            sudo sed -i 's/^#baseurl=/baseurl=/g' "$repo_file"
            sudo sed -i 's|download.example/pub/fedora/linux|mirrors.aliyun.com/fedora|g' "$repo_file"
        fi
    done

    log_success "Fedora 镜像源配置完成"
}

# 配置 CentOS/RHEL 镜像源
setup_centos_mirrors() {
    log_info "配置 CentOS 镜像源..."

    local version=$(rpm -E %{rhel})
    local repo_dir="/etc/yum.repos.d"

    # 备份原有配置
    if [ -d "$repo_dir" ]; then
        sudo cp -r "$repo_dir" "${repo_dir}.backup.$(date +%Y%m%d_%H%M%S)"
    fi

    # CentOS Stream 或 CentOS 7/8
    if [ -f /etc/centos-release ]; then
        sudo sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-*.repo
        sudo sed -i 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.aliyun.com|g' /etc/yum.repos.d/CentOS-*.repo
    fi

    log_success "CentOS 镜像源配置完成"
}

# 配置 Manjaro 镜像源
setup_manjaro_mirrors() {
    log_info "配置 Manjaro 镜像源..."

    # Manjaro 使用 pacman-mirrors 工具
    if command -v pacman-mirrors &> /dev/null; then
        sudo pacman-mirrors -c China
        log_success "Manjaro 镜像源配置完成"
    else
        log_warning "未找到 pacman-mirrors 工具，跳过 Manjaro 镜像配置"
    fi
}

# 配置 pip 镜像源
setup_pip_mirrors() {
    log_info "配置 pip 镜像源..."

    local pip_conf_dir="$HOME/.pip"
    local pip_conf="$pip_conf_dir/pip.conf"

    mkdir -p "$pip_conf_dir"

    cat <<'EOF' > "$pip_conf"
[global]
index-url = https://mirrors.aliyun.com/pypi/simple/
trusted-host = mirrors.aliyun.com

[install]
trusted-host = mirrors.aliyun.com
EOF

    log_success "pip 镜像源配置完成"
}

# 配置 npm 镜像源
setup_npm_mirrors() {
    log_info "配置 npm 镜像源..."

    if command -v npm &> /dev/null; then
        npm config set registry https://registry.npmmirror.com
        log_success "npm 镜像源配置完成"
    else
        log_info "npm 未安装，跳过配置"
    fi
}

# 配置 Docker 镜像源
setup_docker_mirrors() {
    log_info "配置 Docker 镜像加速..."

    # 创建配置文件存储镜像源地址
    local docker_config_dir="$HOME/.docker"
    local mirror_config="$docker_config_dir/mirror.conf"

    mkdir -p "$docker_config_dir"

    # 保存镜像源配置（可自定义修改）
    cat <<'EOF' > "$mirror_config"
# Docker 镜像加速配置
# 修改此文件中的 DOCKER_MIRROR 变量来更换镜像源

# 当前可用的镜像源（2026年5月）
DOCKER_MIRROR="docker.1ms.run"

# 其他备用镜像源（如果上面的失效，可以尝试这些）
# DOCKER_MIRROR="dockerpull.com"
# DOCKER_MIRROR="docker.rainbond.cc"
# DOCKER_MIRROR="docker.fxxk.dedyn.io"

# 使用方法：
# 1. 使用 dp 命令（docker pull 的别名）：
#    dp nginx:alpine
#    等同于：docker pull docker.1ms.run/library/nginx:alpine
#
# 2. 手动指定完整路径：
#    docker pull docker.1ms.run/library/nginx:alpine
#
# 3. 对于非官方镜像（如 bitnami/nginx）：
#    docker pull docker.1ms.run/bitnami/nginx
EOF

    log_success "Docker 镜像源配置已保存到: $mirror_config"

    # 创建 shell 函数配置文件
    local docker_functions="$HOME/.docker/functions.sh"
    cat <<'EOF' > "$docker_functions"
#!/bin/bash
# Docker 镜像加速辅助函数

# 加载镜像源配置
if [ -f "$HOME/.docker/mirror.conf" ]; then
    source "$HOME/.docker/mirror.conf"
fi

# docker pull 加速函数
dp() {
    if [ -z "$1" ]; then
        echo "用法: dp <镜像名>"
        echo "示例: dp nginx:alpine"
        echo "示例: dp bitnami/nginx:latest"
        return 1
    fi

    local image="$1"
    local mirror="${DOCKER_MIRROR:-docker.1ms.run}"

    # 判断是否为官方镜像（不包含 /）
    if [[ ! "$image" =~ / ]]; then
        image="library/$image"
    fi

    echo "使用镜像源: $mirror"
    echo "拉取镜像: $mirror/$image"
    docker pull "$mirror/$image"
}

# docker pull 加速（保留原始标签）
dpl() {
    if [ -z "$1" ]; then
        echo "用法: dpl <镜像名>"
        echo "说明: 拉取后自动重新标记为原始镜像名"
        echo "示例: dpl nginx:alpine"
        return 1
    fi

    local image="$1"
    local mirror="${DOCKER_MIRROR:-docker.1ms.run}"
    local full_image="$image"

    # 判断是否为官方镜像
    if [[ ! "$image" =~ / ]]; then
        full_image="library/$image"
    fi

    echo "使用镜像源: $mirror"
    echo "拉取镜像: $mirror/$full_image"
    docker pull "$mirror/$full_image"

    # 重新标记为原始名称
    if [ $? -eq 0 ]; then
        echo "重新标记为: $image"
        docker tag "$mirror/$full_image" "$image"
        echo "删除镜像源标签..."
        docker rmi "$mirror/$full_image"
        echo "✓ 完成！现在可以使用: docker run $image"
    fi
}

# 显示当前配置的镜像源
docker-mirror() {
    if [ -f "$HOME/.docker/mirror.conf" ]; then
        echo "当前 Docker 镜像源配置："
        echo "---"
        cat "$HOME/.docker/mirror.conf"
        echo "---"
        echo ""
        echo "当前使用: ${DOCKER_MIRROR:-docker.1ms.run}"
    else
        echo "未找到镜像源配置文件"
    fi
}

# 编辑镜像源配置
docker-mirror-edit() {
    ${EDITOR:-vim} "$HOME/.docker/mirror.conf"
    echo "配置已更新，请重新加载 shell 配置："
    echo "  source ~/.bashrc"
}
EOF

    chmod +x "$docker_functions"

    log_success "Docker 辅助函数已创建: $docker_functions"
    log_info ""
    log_info "使用方法："
    echo "  1. 重新加载配置: source ~/.bashrc"
    echo "  2. 拉取镜像: dp nginx:alpine"
    echo "  3. 拉取并重命名: dpl nginx:alpine"
    echo "  4. 查看配置: docker-mirror"
    echo "  5. 修改镜像源: docker-mirror-edit"
    log_info ""
    log_warning "注意: 传统的 registry-mirrors 方式已失效"
    log_info "请使用上述命令或手动指定完整路径"
}

# 主函数
main() {
    echo ""
    echo "╔═══════════════════════════════════════╗"
    echo "║     镜像源配置脚本                    ║"
    echo "║     针对中国大陆环境优化              ║"
    echo "╚═══════════════════════════════════════╝"
    echo ""

    # 检测发行版
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO=$ID
    else
        log_error "无法检测发行版"
        exit 1
    fi

    log_info "检测到发行版: $DISTRO"
    echo ""

    # 根据发行版配置镜像源
    case "$DISTRO" in
        arch)
            setup_arch_mirrors
            ;;
        ubuntu)
            setup_ubuntu_mirrors
            ;;
        debian)
            setup_debian_mirrors
            ;;
        fedora)
            setup_fedora_mirrors
            ;;
        centos|rhel)
            setup_centos_mirrors
            ;;
        manjaro)
            setup_manjaro_mirrors
            ;;
        *)
            log_warning "未知的发行版: $DISTRO"
            log_info "跳过系统镜像源配置"
            ;;
    esac

    echo ""
    log_info "配置常用工具镜像源..."

    # 配置常用工具的镜像源
    setup_pip_mirrors
    setup_npm_mirrors
    setup_docker_mirrors

    echo ""
    log_success "镜像源配置完成！"
    echo ""

    # 根据包管理器更新缓存
    case "$DISTRO" in
        arch|manjaro)
            log_info "更新 pacman 缓存..."
            sudo pacman -Sy
            ;;
        ubuntu|debian)
            log_info "更新 apt 缓存..."
            sudo apt update
            ;;
        fedora|centos|rhel)
            log_info "更新 dnf/yum 缓存..."
            if command -v dnf &> /dev/null; then
                sudo dnf makecache
            else
                sudo yum makecache
            fi
            ;;
    esac

    echo ""
    log_success "所有配置已完成！"
}

# 运行主函数
main "$@"
